/** Audit Ledger style: clean-copy choices expose local output trade-offs, metadata signals, and reversible user decisions. */
import { useEffect, useState } from "react";
import { AlertTriangle, Check, Copy, Download, Eraser, Palette, ShieldCheck, SlidersHorizontal } from "lucide-react";
import { Button } from "@/components/ui/button";
import { canCreateCleanCopy, CleanCopyFormat, cleanCopyFileName, createExifFreeImage, DEFAULT_JPEG_QUALITY, ImageInspection, JPEG_QUALITY_MAX, JPEG_QUALITY_MIN } from "@/lib/image";

type CleanStage = "idle" | "working" | "complete" | "error";
type CopyStage = "idle" | "complete" | "error";

function formatBytes(bytes: number): string { return bytes < 1024 ? `${bytes} B` : bytes < 1024 * 1024 ? `${(bytes / 1024).toFixed(1)} KB` : `${(bytes / (1024 * 1024)).toFixed(1)} MB`; }
function metadataValue(value?: string): string { return value || "Not recorded"; }
function orientationLabel(value?: number): string { if (!value) return "Not recorded"; return ({ 1: "Normal", 3: "Rotated 180°", 6: "Rotated 90° clockwise", 8: "Rotated 90° counter-clockwise" }[value] ?? `EXIF orientation ${value}`); }

async function copySummary(text: string): Promise<void> {
  if (navigator.clipboard?.writeText) { await navigator.clipboard.writeText(text); return; }
  const area = document.createElement("textarea"); area.value = text; area.style.position = "fixed"; area.style.opacity = "0"; document.body.appendChild(area); area.select();
  const copied = document.execCommand("copy"); area.remove(); if (!copied) throw new Error("Clipboard access was unavailable. Select the summary and copy it manually.");
}

export function ImageCleanActions({ sourceFile, inspection }: { sourceFile: File | null; inspection: ImageInspection }) {
  const [cleanFormat, setCleanFormat] = useState<CleanCopyFormat>("jpeg");
  const [jpegQuality, setJpegQuality] = useState(DEFAULT_JPEG_QUALITY);
  const [estimatedBytes, setEstimatedBytes] = useState<number | null>(null);
  const [estimating, setEstimating] = useState(false);
  const [cleanStage, setCleanStage] = useState<CleanStage>("idle");
  const [cleanError, setCleanError] = useState<string | null>(null);
  const [copyStage, setCopyStage] = useState<CopyStage>("idle");
  const [copyError, setCopyError] = useState<string | null>(null);
  const canDownload = Boolean(sourceFile && canCreateCleanCopy(inspection.format, inspection.metadataState));

  useEffect(() => {
    if (!sourceFile || !canDownload) return;
    let active = true;
    setEstimating(true); setEstimatedBytes(null);
    const timer = window.setTimeout(() => {
      void createExifFreeImage(sourceFile, cleanFormat, jpegQuality).then((blob) => { if (active) setEstimatedBytes(blob.size); }).catch(() => { if (active) setEstimatedBytes(null); }).finally(() => { if (active) setEstimating(false); });
    }, 180);
    return () => { active = false; window.clearTimeout(timer); };
  }, [sourceFile, cleanFormat, jpegQuality, canDownload]);

  const privacySummary = ["Private Preflight image privacy summary", "Inspection ran locally in this browser tab.", `EXIF metadata: ${inspection.metadataState === "available" ? "detected" : "not detected"}.`, `Location metadata: ${inspection.exif.hasLocationMetadata ? "detected" : "not detected"}.`, `ICC profile: ${inspection.ancillaryMetadata.hasIccProfile ? "detected and removed in the clean output" : "not detected"}.`, `Text comments: ${inspection.ancillaryMetadata.hasTextComments ? "detected and removed in the clean output" : "not detected"}.`, canDownload ? `Selected clean output: ${cleanFormat.toUpperCase()}${cleanFormat === "jpeg" ? ` at quality ${jpegQuality}` : ""}.` : "No clean copy is offered for this image.", "The original image is not changed or uploaded. This summary excludes filename, image bytes, camera values, and coordinates."].join("\n");

  const download = async () => { if (!sourceFile) return; setCleanStage("working"); setCleanError(null); try { const blob = await createExifFreeImage(sourceFile, cleanFormat, jpegQuality); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = cleanCopyFileName(sourceFile.name, cleanFormat); link.click(); window.setTimeout(() => URL.revokeObjectURL(url), 0); setCleanStage("complete"); } catch (error) { setCleanError(error instanceof Error ? error.message : "The browser could not create the clean copy locally."); setCleanStage("error"); } };
  const copy = async () => { setCopyStage("idle"); setCopyError(null); try { await copySummary(privacySummary); setCopyStage("complete"); } catch (error) { setCopyError(error instanceof Error ? error.message : "Clipboard access was unavailable."); setCopyStage("error"); } };

  return <>
    {canDownload && <><section className="metadata-comparison" aria-labelledby="comparison-title"><div className="metadata-comparison__heading"><span className="eyebrow"><span>COMPARE / 04</span> Metadata ledger</span><h3 id="comparison-title">See what the clean copy removes.</h3></div><div className="metadata-comparison__table"><div className="metadata-comparison__header"><span>Field</span><span>Original</span><span>Clean {cleanFormat.toUpperCase()}</span></div><div><span>EXIF block</span><strong>{inspection.metadataState === "available" ? "Found" : "Present, unreadable"}</strong><strong className="metadata-removed">Removed</strong></div><div><span>Orientation</span><strong>{orientationLabel(inspection.exif.orientation)}</strong><strong className="metadata-removed">Normalized</strong></div><div><span>Camera make</span><strong>{metadataValue(inspection.exif.make)}</strong><strong className="metadata-removed">Removed</strong></div><div><span>Camera model</span><strong>{metadataValue(inspection.exif.model)}</strong><strong className="metadata-removed">Removed</strong></div><div><span>Capture time</span><strong>{metadataValue(inspection.exif.capturedAt)}</strong><strong className="metadata-removed">Removed</strong></div><div><span>Location signal</span><strong>{inspection.exif.hasLocationMetadata ? "Present" : "Not recorded"}</strong><strong className="metadata-removed">{inspection.exif.hasLocationMetadata ? "Removed" : "Not recorded"}</strong></div><div><span>ICC colour profile</span><strong>{inspection.ancillaryMetadata.hasIccProfile ? "Detected" : "Not recorded"}</strong><strong className="metadata-removed">{inspection.ancillaryMetadata.hasIccProfile ? "Removed" : "Not recorded"}</strong></div><div><span>Text comments</span><strong>{inspection.ancillaryMetadata.hasTextComments ? "Detected" : "Not recorded"}</strong><strong className="metadata-removed">{inspection.ancillaryMetadata.hasTextComments ? "Removed" : "Not recorded"}</strong></div></div></section>
    <section className="image-clean-copy" aria-live="polite"><div><span className="eyebrow"><span>DECIDE / 05</span> Local re-encode</span><h3>Remove metadata and download a clean copy.</h3><p>Choose a compact JPEG or a lossless PNG. The original image is not changed.</p><div className="clean-format-picker" role="group" aria-label="Clean-copy format"><button type="button" aria-pressed={cleanFormat === "jpeg"} className={cleanFormat === "jpeg" ? "is-selected" : ""} onClick={() => { setCleanFormat("jpeg"); setCleanStage("idle"); }}>JPEG <small>Smaller · adjustable quality</small></button><button type="button" aria-pressed={cleanFormat === "png"} className={cleanFormat === "png" ? "is-selected" : ""} onClick={() => { setCleanFormat("png"); setCleanStage("idle"); }}>PNG <small>Lossless · preserves transparency</small></button></div>{cleanFormat === "jpeg" && <label className="jpeg-quality-control"><span><SlidersHorizontal aria-hidden="true" /> JPEG quality <strong>{jpegQuality}</strong></span><input type="range" min={JPEG_QUALITY_MIN} max={JPEG_QUALITY_MAX} value={jpegQuality} onChange={(event) => { setJpegQuality(Number(event.target.value)); setCleanStage("idle"); }} /><small>Lower quality generally means a smaller file and more compression.</small></label>}<details className="advanced-cleanup"><summary><Palette aria-hidden="true" /> Advanced container cleanup</summary><p>Colour profiles (ICC) guide colour interpretation; text comments can carry labels or notes. A clean browser re-encode removes both when found.</p><div><span>ICC profile: <strong>{inspection.ancillaryMetadata.hasIccProfile ? "Detected — will be removed" : "Not detected"}</strong></span><span>Text comments: <strong>{inspection.ancillaryMetadata.hasTextComments ? "Detected — will be removed" : "Not detected"}</strong></span></div></details>{estimating ? <p className="clean-estimate">Estimating local output size…</p> : estimatedBytes !== null ? <p className="clean-estimate">Estimated clean {cleanFormat.toUpperCase()}: <strong>{formatBytes(estimatedBytes)}</strong>{cleanFormat === "jpeg" ? ` at quality ${jpegQuality}` : ""}.</p> : <p className="clean-estimate">Size estimate becomes available before download.</p>}{cleanStage === "complete" && <p className="image-clean-copy__success"><ShieldCheck aria-hidden="true" /> Clean {cleanFormat.toUpperCase()} downloaded locally. Review that new file before sharing.</p>}{cleanError && <p className="image-clean-copy__error"><AlertTriangle aria-hidden="true" /> {cleanError}</p>}</div><Button className="action-button" onClick={() => void download()} disabled={cleanStage === "working" || estimating}><Eraser aria-hidden="true" /> {cleanStage === "working" ? `Creating clean ${cleanFormat.toUpperCase()}` : `Download clean ${cleanFormat.toUpperCase()}`}<Download aria-hidden="true" /></Button></section></>}
    <section className="image-privacy-summary" aria-labelledby="privacy-summary-title"><div><span className="eyebrow"><span>SHARE / 06</span> Privacy summary</span><h3 id="privacy-summary-title">A concise local handling note.</h3><p>{privacySummary.split("\n").slice(1).join(" ")}</p>{copyStage === "complete" && <p className="image-privacy-summary__success"><Check aria-hidden="true" /> Privacy summary copied to clipboard.</p>}{copyError && <p className="image-privacy-summary__error"><AlertTriangle aria-hidden="true" /> {copyError}</p>}</div><Button variant="outline" onClick={() => void copy()}><Copy aria-hidden="true" /> Copy privacy summary</Button></section>
  </>;
}
